/**
 * dt-ui's palettes, with one representative colour each.
 *
 * GENERATED by scripts/generate-palettes.mjs from dt-ui's palettes.css and
 * Tailwind's theme.css. Do not edit: rerun the generator when dt-ui retunes a
 * palette, so the swatch a developer picks stays the colour they get.
 */

export interface Palette {
  /** Value of the storefront's `data-dt-palette` attribute. */
  readonly name: string;
  /** sRGB hex of the palette's accent, for a terminal swatch. */
  readonly hex: string;
}

export const PALETTES: readonly Palette[] = [
  {
    name: "indigo",
    hex: "#4f39f6"
  },
  {
    name: "cobalt",
    hex: "#155dfc"
  },
  {
    name: "midnight",
    hex: "#155dfc"
  },
  {
    name: "ocean",
    hex: "#0084d1"
  },
  {
    name: "lagoon",
    hex: "#0092b8"
  },
  {
    name: "teal",
    hex: "#009689"
  },
  {
    name: "jade",
    hex: "#009966"
  },
  {
    name: "forest",
    hex: "#009966"
  },
  {
    name: "moss",
    hex: "#00a63e"
  },
  {
    name: "lime",
    hex: "#7ccf00"
  },
  {
    name: "citrus",
    hex: "#fe9a00"
  },
  {
    name: "honey",
    hex: "#f0b100"
  },
  {
    name: "sunset",
    hex: "#f54900"
  },
  {
    name: "ember",
    hex: "#e7000b"
  },
  {
    name: "coral",
    hex: "#ec003f"
  },
  {
    name: "rose",
    hex: "#ec003f"
  },
  {
    name: "blossom",
    hex: "#e60076"
  },
  {
    name: "orchid",
    hex: "#c800de"
  },
  {
    name: "violet",
    hex: "#7f22fe"
  },
  {
    name: "royal",
    hex: "#9810fa"
  },
  {
    name: "plum",
    hex: "#9810fa"
  },
  {
    name: "slate",
    hex: "#45556c"
  },
  {
    name: "graphite",
    hex: "#52525c"
  },
  {
    name: "sand",
    hex: "#57534d"
  }
];

export const DEFAULT_PALETTE = 'indigo';

export function isPalette(name: string): boolean {
  return PALETTES.some((p) => p.name === name);
}

export type Appearance = 'light' | 'dark' | 'system';
export const APPEARANCES: readonly Appearance[] = ['light', 'dark', 'system'];
